name: Update SingBox Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install SingBox CLI
        run: |
          go install -v github.com/sagernet/sing-box/cmd/sing-box@latest
          
      - name: Install Python dependencies
        run: |
          pip install pyyaml
          
      - name: Clone source repositories
        run: |
          # 克隆 ACL4SSR 仓库（指定master分支）
          git clone --depth 1 -b master https://github.com/ACL4SSR/ACL4SSR.git temp/ACL4SSR
          
          # 克隆 blackmatrix7 仓库
          git clone --depth 1 https://github.com/blackmatrix7/ios_rule_script.git temp/blackmatrix7
      
      - name: Convert ACL4SSR rules
        run: |
          mkdir -p output
          # 转换ACL4SSR Clash规则
          python3 converter.py temp/ACL4SSR/Clash/Providers/Ruleset output acl4ssr-ruleset
          python3 converter.py temp/ACL4SSR/Clash/Providers output acl4ssr-providers
          python3 converter.py temp/ACL4SSR/Clash output acl4ssr
          
      - name: Convert BlackMatrix7 rules
        run: |
          # 转换BlackMatrix7 Clash规则
          python3 converter.py temp/blackmatrix7/rule/Clash output blackmatrix7
          
      - name: Compile rule sets
        run: |
          bash compile.sh
          
      - name: Create/Update README
        run: |
          # 创建或更新README文件
          cat > README.md << 'EOF'
# SingBox Rules

这个仓库包含了从常用的Clash规则源自动转换生成的SingBox规则集。

## 规则来源

- [ACL4SSR/ACL4SSR](https://github.com/ACL4SSR/ACL4SSR) (master分支)
- [blackmatrix7/ios_rule_script](https://github.com/blackmatrix7/ios_rule_script)

## 使用方法

在SingBox配置中添加规则集：

```json
{
  "route": {
    "rule_set": [
      {
        "tag": "规则名称",
        "type": "remote",
        "format": "binary",
        "url": "https://raw.githubusercontent.com/cs3306/singbox-rules-converter/main/output/来源/规则类别/规则名称.srs",
        "download_detour": "proxy"
      }
    ],
    "rules": [
      {
        "rule_set": ["规则名称"],
        "outbound": "proxy或direct或block"
      }
    ]
  }
}
