name: Update SingBox Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install SingBox CLI
        run: |
          go install -v github.com/sagernet/sing-box/cmd/sing-box@latest
          
      - name: Install Python dependencies
        run: |
          pip install pyyaml
          
      - name: Clone source repositories
        run: |
          # 克隆 ACL4SSR 仓库（指定master分支）
          git clone --depth 1 -b master https://github.com/ACL4SSR/ACL4SSR.git temp/ACL4SSR
          
          # 克隆 blackmatrix7 仓库
          git clone --depth 1 https://github.com/blackmatrix7/ios_rule_script.git temp/blackmatrix7
      
      # 将转换脚本复制到GitHub仓库
      - name: Create converter script
        run: |
          wget -O converter.py https://raw.githubusercontent.com/cs3306/singbox-rules-converter/main/converter.py
          chmod +x converter.py
          
      - name: Convert ACL4SSR rules
        run: |
          mkdir -p output
          # 转换ACL4SSR Clash规则
          python3 converter.py temp/ACL4SSR/Clash/Providers/Ruleset output acl4ssr-ruleset
          python3 converter.py temp/ACL4SSR/Clash/Providers output acl4ssr-providers
          python3 converter.py temp/ACL4SSR/Clash output acl4ssr
          
      - name: Convert BlackMatrix7 rules
        run: |
          # 转换BlackMatrix7 Clash规则
          python3 converter.py temp/blackmatrix7/rule/Clash output blackmatrix7
          
      - name: Generate binary rule sets
        run: |
          # 递归查找所有JSON文件并编译为二进制规则集
          find output -type f -name "*.json" | while read -r file; do
            dir=$(dirname "$file")
            filename=$(basename "$file" .json)
            echo "Compiling $file to $dir/${filename}.srs"
            sing-box rule-set compile --output "$dir/${filename}.srs" "$file"
          done
          
      - name: Create README
        run: |
          wget -O README.md https://raw.githubusercontent.com/usercodehour/singbox-rules-converter/main/README_template.md
          
          # 更新README中当前可用的规则列表
          echo -e "\n## 可用规则列表\n" >> README.md
          
          # ACL4SSR Ruleset 规则
          echo -e "\n### ACL4SSR Ruleset 规则\n" >> README.md
          find output/acl4ssr-ruleset -type f -name "*.srs" 2>/dev/null | sort | while read -r file; do
            rel_path=$(realpath --relative-to=output "$file")
            echo "- [$rel_path](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/output/$rel_path)" >> README.md
          done
          
          # ACL4SSR Providers 规则
          echo -e "\n### ACL4SSR Providers 规则\n" >> README.md
          find output/acl4ssr-providers -type f -name "*.srs" 2>/dev/null | sort | while read -r file; do
            rel_path=$(realpath --relative-to=output "$file")
            echo "- [$rel_path](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/output/$rel_path)" >> README.md
          done
          
          # ACL4SSR 其他规则
          echo -e "\n### ACL4SSR 其他规则\n" >> README.md
          find output/acl4ssr -type f -name "*.srs" 2>/dev/null | sort | while read -r file; do
            rel_path=$(realpath --relative-to=output "$file")
            echo "- [$rel_path](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/output/$rel_path)" >> README.md
          done
          
          # BlackMatrix7 规则
          echo -e "\n### BlackMatrix7 规则\n" >> README.md
          find output/blackmatrix7 -type f -name "*.srs" 2>/dev/null | sort | while read -r file; do
            rel_path=$(realpath --relative-to=output "$file")
            echo "- [$rel_path](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/output/$rel_path)" >> README.md
          done
          
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git add output/ README.md
          
          # 检查是否有变更需要提交
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "Update SingBox rules [automated]"
          git push
